version: '3.8'
services:
  app:
    image: lolarp/pibas-server-app:latest
    ports:
      - 5500:5500
    command: npm start index.js
  client:
    image: lolarp/pibas-server-client:latest
    ports:
      - 3000:3000
    command: npm run start
    links:
      - app
